app/src/Entity/Genre.php
<?php

namespace App\Entity;

use App\Repository\GenreRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GenreRepository::class)]
class Genre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $tmdb_id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTmdbId(): ?int
    {
        return $this->tmdb_id;
    }

    public function setTmdbId(int $tmdb_id): static
    {
        $this->tmdb_id = $tmdb_id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }
}

app/src/Controller/GenreController.php
<?php

namespace App\Controller;

use App\Repository\GenreRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class GenreController extends AbstractController
{
    #[Route('/genre', name: 'app_genre')]
    public function index(GenreRepository $genreRepository): Response
    {
        return $this->render('genre/list.html.twig', [
            'genres' => $genreRepository->findAll(),
        ]);
    }
}

app/templates/genre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello GenreController!{% endblock %}

{% block body %}
    <style>
        .wrapper {
            margin: 1em auto;
            width: 95%;
        }
    </style>

    <div class="wrapper">
        <h1>All genres</h1>
        <table class="table table-striped table-hover table-bordered">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Tmdb ID</th>
                <th scope="col">Name</th>
            </tr>
            </thead>
            <tbody>
            {% for genre in genres %}
                <tr>
                    <td>{{ loop.index }}</td>
                    <td>{{ genre.tmdbId }}</td>
                    <td>{{ genre.name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}